"""empty message

Revision ID: 73353fd6b688
Revises: e908f0dbd150
Create Date: 2025-06-13 13:04:28.387935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73353fd6b688'
down_revision = 'e908f0dbd150'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issue_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emp_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('issue', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('date_of', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['emp_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('issue_report', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_issue_report_emp_id'), ['emp_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_issue_report_issue'), ['issue'], unique=False)
        batch_op.create_index(batch_op.f('ix_issue_report_reason'), ['reason'], unique=False)
        batch_op.create_index(batch_op.f('ix_issue_report_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('attendance__tracking', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance__tracking_emp_id'))
        batch_op.drop_index(batch_op.f('ix_attendance__tracking_issue'))
        batch_op.drop_index(batch_op.f('ix_attendance__tracking_reason'))
        batch_op.drop_index(batch_op.f('ix_attendance__tracking_user_id'))

    op.drop_table('attendance__tracking')
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employee_location_id'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employee_location_id'), ['location_id'], unique=False)

    op.create_table('attendance__tracking',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('emp_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('issue', sa.TEXT(), nullable=False),
    sa.Column('reason', sa.TEXT(), nullable=False),
    sa.Column('date_of', sa.DATE(), nullable=False),
    sa.ForeignKeyConstraint(['emp_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attendance__tracking', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendance__tracking_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance__tracking_reason'), ['reason'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance__tracking_issue'), ['issue'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance__tracking_emp_id'), ['emp_id'], unique=False)

    with op.batch_alter_table('issue_report', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_issue_report_user_id'))
        batch_op.drop_index(batch_op.f('ix_issue_report_reason'))
        batch_op.drop_index(batch_op.f('ix_issue_report_issue'))
        batch_op.drop_index(batch_op.f('ix_issue_report_emp_id'))

    op.drop_table('issue_report')
    # ### end Alembic commands ###
