"""empty message

Revision ID: e908f0dbd150
Revises: 
Create Date: 2025-06-12 23:07:35.273857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e908f0dbd150'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_location_location'), ['location'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('date_of_hire', sa.Date(), nullable=False),
    sa.Column('date_of_term', sa.Date(), nullable=True),
    sa.Column('emp_active', sa.Boolean(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employee_first_name'), ['first_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_employee_last_name'), ['last_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_employee_location_id'), ['location_id'], unique=False)

    op.create_table('attendance__tracking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emp_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('issue', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('date_of', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['emp_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attendance__tracking', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendance__tracking_emp_id'), ['emp_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance__tracking_issue'), ['issue'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance__tracking_reason'), ['reason'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance__tracking_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance__tracking', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance__tracking_user_id'))
        batch_op.drop_index(batch_op.f('ix_attendance__tracking_reason'))
        batch_op.drop_index(batch_op.f('ix_attendance__tracking_issue'))
        batch_op.drop_index(batch_op.f('ix_attendance__tracking_emp_id'))

    op.drop_table('attendance__tracking')
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employee_location_id'))
        batch_op.drop_index(batch_op.f('ix_employee_last_name'))
        batch_op.drop_index(batch_op.f('ix_employee_first_name'))

    op.drop_table('employee')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_location_location'))

    op.drop_table('location')
    # ### end Alembic commands ###
